#!/bin/sh
sed -i 's/root::0:0:99999:7:::/root:$1$Csqc6adE$DuBCyECxab9oIx9oy/SV91:19746:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$Csqc6adE$DuBCyECxab9oIx9oy/SV91:19746:0:99999:7:::/g' /etc/shadow
exit 0
