#!/bin/sh

sed -i 's/root::0:0:99999:7:::/root:$1$1YHqgZLV$uX.JQ/17G6eGEzRbBIDpw0:20054:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$1YHqgZLV$uX.JQ/17G6eGEzRbBIDpw0:20054:0:99999:7:::/g' /etc/shadow

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
